---
title: tseda in the notebook
description: Example of tseda in the notebook
author:
  - Per Unneberg
execute:
  eval: true
  cache: false
jupyter:
  jupytext:
    formats: ipynb,qmd
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.18.1
  kernelspec:
    display_name: Python (tseda uv)
    language: python
    name: tseda-uv
---

This notebook provides a minimum working example of how to load a
tseda file into a notebook and how to make use of the application
widgets as standalone objects. The example is based on the test file
`test.trees.tsdate.tseda` that can be found in the tests data folder.

Note that the API is still in development and that this notebook is
meant to showcase basic functionality as currently implemented. The
data model is based on the [DataStore design
pattern](https://panel.holoviz.org/tutorials/intermediate/structure_data_store.html),
where raw data resides in a data store, and filtered data is consumed
by views to present different aspects of the data. The views are
composed by reusable components and widgets.

```{python}
%load_ext autoreload
%autoreload 2
```

```{python}
from bokeh.plotting import show, output_notebook
output_notebook(hide_banner=True)
```

The `datastore` module defines the classes that are used by all
application pages, namely that

- `SampleSetsTable`: manages and displays information about sample
  sets
- `IndividualsTable`: handles individual data, such as population and
  sample set assignments
- `DataStore`: provides access to the underlying `TreeSequence` data
  as well as the tables described above

`model` defines a model of the tree sequence data called `TSModel`.
This is a modified version of
[`tsbrowse.model.TSModel`](https://github.com/tskit-dev/tsbrowse/blob/main/tsbrowse/model.py).

## Setting up the datastore

The `DataStore` class is the fundamental data structure that provides
data for views and filters. It is produced by parsing an instance of
the `TSModel` class. We can instantiate a `DataStore` object from a
`TSModel` object or a path to a `tseda` file. Note that the input
`tseda` file must have been generated by running `tseda preprocess` on
an input compressed tree sequence file. The following two code blocks
are equivalent.

## Module setup

First load the relevant `tseda` modules and `panel` extension for
tables.

```{python}
from tseda import datastore, model
import panel as pn
pn.extension("tabulator")
```

```{python}
# Generate a datastore object from a file path
ds = datastore.DataStore(tsm="../tests/data/test.trees.tsdate.tseda")
```

```{python}
# Alternatively, pass a TSModel object
tsm = model.TSModel("../tests/data/test.trees.tsdate.tseda")
ds = datastore.DataStore(tsm=tsm)
```

`ds` has three attributes `sample_sets_table`, `individuals_table`,
and `tsm` that point to instances of `SampleSetsTable`,
`IndividualsTable`, and `TSModel`, respectively.

The sample sets table defines the [sample
sets](https://tskit.dev/tskit/docs/stable/stats.html#sample-sets-and-indexes)
used in the analyses. The starting table consists of the populations
defined in the input tree sequence file, but custom sample sets can be
added later on. Names and colors can be edited.

```{python}
ds.sample_sets_table
```

Briefly, the indivduals table displays the individual samples and
corresponding metadata, such as population, name, longitude, and
latitude.

```{python}
# FIXME: individuals table should be represented as a widget
ds.individuals_table.table.head(3)
```

Note the distinction between `population`, which is immutable and
corresponds to the original population assignment in the input tree
sequence file, and `sample_set_id`, which is a placeholder for the
**current** population assignment. By modifying this column, we can
make arbitrary population (sample set) assignments to individual
samples. Finally, the `selected` column lets us exclude samples from
subsequent analyses.

To actually display the widgets we will make use of the `vpages`
module as detailed in the following section.

## Widgets

The `tseda` interactive app consists of thematic pages that in turn
are made up of widgets that present different views of the data. The
widgets can be accessed and used directly in the notebook. We first
import the widgets module.

```{python}
from tseda import widgets
```

The available widgets are available in the `__all__` variable

```{python}
widgets.__all__
```

```{python}
import os
MONKEYFLOWER=os.environ["MONKEYFLOWER"]
ds = datastore.DataStore(tsm=MONKEYFLOWER)
```

Common to all widgets is that they require a datastore argument. In
addition, there are options for controlling figure appearance, size,
font size, and more. We first demonstrate the functionality using the
`IGNNVBar` widget before going through the remaining widgets.

### Basic functionality with IGNNVBar

The `IGNNVBar` shows a vertically stacked bar plot of genealogical
nearest neighbor (GNN) proportions for each individual. It resembles
an admixture plot. The colors represent the sample sets defined in the
sample sets table.

By passing the parsed datastore object we can easily create an
instance of the widget.

```{python}
vbar = widgets.IGNNVBar(datastore=ds)
```

```{python}
vbar
```

All widgets come equipped with a toolbar with a set of [Bokeh
tools](https://docs.bokeh.org/en/latest/docs/reference/models/tools.html),
here located in the right hand side. In you hover over the tools,
you'll see that the included tools here are pan, rectangle select,
wheel zoom, save, reset and hover.

The widgets also take options for controlling figure size, font size
and more:

```{python}
widgets.IGNNVBar(datastore=ds, base_font_size=10,
                 height=300, sizing_mode="stretch_width")
```

Most of the options are class attributes that derive from the
[panel.Param](https://param.holoviz.org/) parameter class. You can
list all available parameters for a widget through the `param`
attribute:

```{python}
vbar.param
```

### IGNNHaplotype

Whereas the `IGNNVBar` plot shows the GNN proportions over the entire
chromosome, `IGNNHaplotype` shows the GNN proportions along a
chromosome for an individual of choice.

```{python}
hap = widgets.IGNNHaplotype(datastore=ds, height=200, base_font_size=20)
hap
```

As the calculation of GNN proportions over the chromosome is
time-consuming, by default no individual is selected. You can select
an individual by setting the `individual_id` parameter:

```{python}
hap.individual_id = 0
```

```{python}
hap
```

### OnewayStats

The `OnewayStats` widget plots statistics that apply to single sample
sets, such as diversity or Tajima's D.

```{python}
p = widgets.OnewayStats(datastore=ds, caption=False)
p
```

### MultiwayStats

**NB**: the MultiwayStats API is unwieldy and currently undergoing
changes.

Similarly, `MultiwayStats` lets us plot statistics that *compare*
sample sets, such as `Fst` or `divergence`. Since the number of
comparisons grows quickly with the number of sample sets, the
requested comparisons have to be set manually.

```{python}
p = widgets.MultiwayStats(datastore=ds, statistic="divergence", sizing_mode="stretch_width")
p.comparisons.value = ["0 & 1", "0 & 2", "0 & 3"]
p.mode = "branch"
p
```

### Structure plots

The structure module consists of a number of plots to quickly plot
heatmap comparisons between samples and sample sets.

`IndividualGNNFigure` shows a heatmap comparing all-vs-all samples. By
default the GNN values are Z-transformed.

```{python}
widgets.IndividualGNNFigure(datastore=ds)
```

`MeanGNNFigure` in turn averages GNN values over each population. This
plot is similar to Figure 4 in Kelleher et al 2019.

```{python}
p = widgets.MeanGNNFigure(datastore=ds)
```

```{python}
widgets.MeanGNNFigure(datastore=ds)
```

Finally, `FstFigure` plots a heatmap of average Fst differences
between populations.

```{python}
widgets.FstFigure(datastore=ds, zscore=False)
```

## Accessing vpages

We have just gone through `tseda`s widgets. These reusable components
are used to build the application pages defined in the `vpages`
module. We can list the available pages by accessing the `PAGES`
attribute.

```{python}
from tseda import vpages
vpages.PAGES
```

Every page is instantiated by passing along the `ds` object, as we
show in the subsequent sections.

### Overview

The overview page summarizes the tree sequence object.

```{python}
ov = vpages.PAGES[0](datastore=ds)
ov
```

### Individuals page

The individuals page displays three widgets:

1. a map with sampling locations
2. the sample set table
3. the individuals table.

```{python}
indp = vpages.PAGES[1](datastore=ds)
indp
```

Each widget can be accessed by calling the corresponding attributes,
which here are `geomap`, `sample_sets_table`, and `individuals_table`.

The individuals page also has a `sidebar` function which is used in
the application to modify tables, assign new sample sets and so on.
This functionality does not yet work in the notebook setting however,
so any modification of the datastore object must be done by editing
the object manually.

### Structure

The structure page summarizes population-wide genealogical nearest
neighbor (GNN) values and $F_{st}$.

```{python}
struct = vpages.PAGES[2](datastore=ds)
struct
```

### Individual GNN

The individual GNN page displays three widgets:

1. a map with sampling locations
2. a bar plot of individual-based GNN values, based on the current
   sample set definitions
3. a widget, initially empty, for plotting chromosome-level GNN values

```{python}
ignn = vpages.PAGES[3](datastore=ds)
ignn
```

### Statistics

[Tree sequence
statistics](https://tskit.dev/tskit/docs/stable/stats.html) come in
two flavors, one-way that are defined over single sample sets, and
multi-way that compare two or more sample sets. The one-way statistics
are accessible via the `oneway` attribute:

```{python}
stats = vpages.PAGES[4](datastore=ds)
stats.oneway
```

For multi-way statistics we need to set which sample sets to compare.
Here, we can make use of the `sidebar` functionality, or set sample
set groups, formatted (exactly) as `INDEX1 & INDEX2`:

```{python}
stats.multiway.comparisons.value = ['0 & 1', '0 & 2']
stats.multiway
```

Here, the indexes correspond to sample set ids.

### Trees

Finally, we can draw trees accessed by genomic position or index in
the tree sequence:

```{python}
#| eval: true
trees = vpages.PAGES[5](datastore=ds)
trees.data.position = 10_000
trees
```

```{python}
trees.sidebar()
```

The slider can be used to modify the current position. The trees page
actually renders the `trees.data` attribute, which is where we can
also set tree attributes manually. For instance, to increase the
number of shown trees to three, we can set
`trees.data.num_trees.value=3`.

## Conclusion

This notebook shows the basic functionality of `tseda` plotting
widgets.
