# -*- yaml -*-
name: Build documentation

on:
  push:
    branches:
      - main
      - quarto
    tags:
      - "v*"
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build site
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - name: Cancel Previous Runs
        if: ${{ !env.ACT }}
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.55.0
          cache: true
          environments: quarto

      - run: echo "QUARTO_PYTHON=${GITHUB_WORKSPACE}/.pixi/envs/quarto/bin/python" >> $GITHUB_ENV

      - name: Render project without publishing
        env:
          QUARTO_PRINT_STACK: true
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          pixi run rd
          echo "QUARTO_OUTPUT=docs/_site" >> $GITHUB_ENV

      - name: Publish to GitHub Pages
        env:
          GITHUB_EMAIL: quarto-github-actions-publish@example.com
          GITHUB_USERNAME: gh_action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PRINT_STACK: true
        if: ${{ github.ref_name == 'main' || github.ref_name == 'quarto' }}
        run: |
          git config --global user.email "${{ env.GITHUB_EMAIL }}"
          git config --global user.name "${{ env.GITHUB_USERNAME }}"
          quarto publish gh-pages --no-browser
